### ISSUE TITLE
What license is on the groovy scripts in this repository?

### ISSUE THREAD

**Issue by electrofelix** [cloudbees/jenkins-scripts#88]
Hi, wondering what license covers the files in this repository? There doesn't appear to be any that is applied so I'm not sure I can safely look at the contents of these scripts for ideas on how to solve specific issues.

**Comment by electrofelix** [comment]
Anyone able to comment on the above connection?

**Comment by mschuijer** [comment]
I don't think there is any license, if you mean you would like guarantees or compensation for when things go wrong. The scripts are provided as helpful tools but it is up to you to wield them and test them in a safe environment first to make sure they do what you want them to.

**Comment by electrofelix** [comment]
@mschuijer I meant what license can I use them under? if it's not under any license AFAIK I can't actually use anythink because it's copyright of the script owner and I have no rights to take and use.

**Comment by mschuijer** [comment]
The script is shared with everyone who can read and I can see it even when not logged in so that shows to me it is public and not under any license.
As mentioned in the readme of this repo "_The scripts in this repository can be run in Jenkins script console: Manage Jenkins > Script Console. Most work on any Jenkins Enterprise instance, while some are specific to CloudBees Jenkins Operations Center (CJOC)._" 
Common sense dictates that this can be used as you wish. It's not like you can get a commercial advantage out of this so I would not worry about this at all.

**Comment by electrofelix** [comment]
@mschuijer unfortunately https://stackoverflow.com/a/13669816/1597808 and https://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html make it quite clear that code without a license is 'All rights reserved' and that means I can't lift any examples from here to use without breaking copyright. This tends to be a common interpretation of the copyright law.

I understand the intent here is to make the examples available for public usage, but no license means that it's not actually public domain. To be public domain it requires an explicit statement in the code saying it's public domain, MIT, BSD, or something else.

**Comment by bitwiseman** [comment]
@electrofelix 
You beat me to explaining that common sense doesn't dictate legal matters. 😄 

CloudBees needs to clarify it's position in relation to these scripts and at minimum as LICENSE.md to this repo, and preferably also to each file.  

With DevOps World | Jenkins World coming up, many CloudBees folks are very busy. It may take a bit for this issue to be resolved to your satisfaction, but I will start a thread including @schottsfired 
and @kmadel.

**Comment by mschuijer** [comment]
@electrofelix  Thanks for pointing that out, I was not aware of it. 
I will also say that 'as many as half [of people publishing code here]' are also not aware of it and '_this situation exists because the founders of GitHub want to ease code sharing. They were worried that selecting a license for a new project was so difficult that requiring new project initiators would be a barrier to the adoption of GitHub_' means that it is partly the fault of GitHub that so few people add a license to their public projects. The articles show the issue is wider than just this repo and repo-owner.
So would you really skip using the scripts made available here by CloudBees, to be used with your CloudBees Jenkins software that you have purchased a license for already? That's up to you of course, but I do not feel bothered about it.
@bitwiseman Good that you involve them; I would think their legal department is available even during an event or possibly even especially so they can boast at the event they did something about this ;)
About the common sense part: it doesn't dictate legal matters, I'll grant you that. It does not make any sense though that CloudBees would suddenly try and sue you for using their software with these additional scripts they made available. Since this is the type of world we live in they should add the license terms of course, eventually, just in case.

**Comment by bitwiseman** [comment]
@electrofelix  Enjoy!
